### ISSUE TITLE
Gutters not working

### ISSUE THREAD

**Issue by tfsomrat** [karolis-sh/tailwind-bootstrap-grid#121]
Hey, I am trying to change the gutter with `g-*` class. but it's not generating any CSS at all. how to use it? (I am using the tailwind container, not this plugin container)

only `g-0` works, but I want `g-2/3/4/5`

![image](https://user-images.githubusercontent.com/58769763/221340384-85396c1b-6577-4172-acc9-162aba094b59.png)

**Comment by karolis-sh** [comment]
Hey, you need to pass those extra gutters you want (https://github.com/karolis-sh/tailwind-bootstrap-grid#options), as only `0` is a predefined default value.
