### ISSUE TITLE
Please add way to configure margin-approach

### ISSUE THREAD

**Issue by 7iomka** [karolis-sh/tailwind-bootstrap-grid#122]
Hi. I love bootstrap grid, but I like `margin-top` for elements instead of `margin-bottom`, how like bootstrap authors.
So, now If I have this type of code, I have wrong behaviour on interaction.
```
<div>
<button style="height: 20px">some clickable</button>
<div class="row gy-20">....</div>
</div>
```

Because row has negative margin and goes after button it content has a larger index and overlaps the button if it does not have a directly given index.
With margin-bottom on row I don't have this issue in most cases.
So, instead of copy-paste source code and to change only this styles, maybe you will introduce a param to use marginBottom instead for those who like me wants this?
Thanks.

**Comment by 7iomka** [comment]
Neither of these solutions is correct.
Proposing to zero indent on the row will cause you to get an extra indent on the block as a whole, because a negative indent on the row will cancel out a positive indent on the cells.
The second suggestion looks inappropriate and overcomplicates the use of the layout, because this button can be in a different section but just be at a distance smaller than the negative indent on its neighbor's row.

Honestly, I don't know how to solve this properly.
In the case of using the indent method at the bottom and not at the top, the next element will always have a larger z-index so there will be no problem.
But we will most likely have a problem in the sections that calculate scrollHeight, since indenting from below with a negative value will increase scrollHeight by that amount, although we don't expect this.
Both are bad, but the problem with the next element overlapping the previous one is more significant.

**Comment by karolis-sh** [comment]
Anyway, this plugin is meant to work like Bootstrap and your problem seems to be a bit different, so I'll be closing this.
