### ISSUE TITLE
Support TypeScript

### ISSUE THREAD

**Issue by camcam2605** [karolis-sh/tailwind-bootstrap-grid#129]
Can support TypeScript for this library ?

**Comment by MickL** [comment]
There are currently two problems:

1. Eslint complains that require() is not allowed
2. When using import instead the compiler is complaining that not declaration file is found

<img width="1193" alt="Bildschirmfoto 2023-11-14 um 17 45 42" src="https://github.com/karolis-sh/tailwind-bootstrap-grid/assets/5103210/4855dc72-82f4-46d3-8957-075bced56120">

@karolis-sh

**Comment by karolis-sh** [comment]
Typescript types have just been added with `5.1.0` version.

@MickL yes, use `import`, did a quick test this should work:

`tailwind.config.ts`

```ts
import tailwindBootstrapGrid from "tailwind-bootstrap-grid";

/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {},
  },
  corePlugins: {
    container: false,
  },
  plugins: [
    tailwindBootstrapGrid({
      containerMaxWidths: {
        sm: "540px",
        md: "720px",
        lg: "960px",
        xl: "1140px",
      },
    }),
  ],
};
```
