### ISSUE TITLE
Child Container padding styles overrides by row styles

### ISSUE THREAD

**Issue by v-kryvenda** [karolis-sh/tailwind-bootstrap-grid#132]
container > row > container

1. First container - https://i.imgur.com/9XH5FJs.png
2. The second container contains x2 padding size - https://i.imgur.com/9DDfjk3.png

**Comment by karolis-sh** [comment]
True, but that's how actual Bootstrap works and this library aims to mimic its functionality. So, I'm going to assume that it is the intended outcome.
