### ISSUE TITLE
How to disable container core plugin?

### ISSUE THREAD

**Issue by MickL** [karolis-sh/tailwind-bootstrap-grid#136]
I am getting the following error:

> WARN  ⚠️  The container core plugin is enabled and you're also generating .container class with the tailwind-bootstrap-grid plugin. This might lead to unexpected styling issues, disable either of one.

But how to disable the container core plugin? The readme links to a section of a page that does not exist: https://tailwindcss.com/docs/container#disabling-entirely

Maybe also update the readme for everyone to come :)

**Comment by karolis-sh** [comment]
Yeah, you need to disable it as a core plugin:

```
        corePlugins: {
          container: false,
        },
```

I remember this has changed over the lifetime of tailwindcss, and thus I just didn't want to maintain this information.
