### ISSUE TITLE
Demo 404

### ISSUE THREAD

**Issue by iljamm** [karolis-sh/tailwind-bootstrap-grid#147]
When clicking on the Demo link in the README it takes to a 404 

Site Not Found

![image](https://github.com/karolis-sh/tailwind-bootstrap-grid/assets/20164908/4e9ad1ca-a9ac-4feb-9f80-38280e775db0)

**Comment by karolis-sh** [comment]
Thanks for the heads up! The link was updated https://tailwind-bootstrap-grid.netlify.app/
