### ISSUE TITLE
Support for !important

### ISSUE THREAD

**Issue by radovanobal** [karolis-sh/tailwind-bootstrap-grid#71]
When you set a custom gutter size the no gutter option no longer takes effect since it's set without a !importnat but the custom gutter size does have a !important
![Screenshot from 2021-01-28 11-37-18](https://user-images.githubusercontent.com/60649057/106126277-78b65480-615d-11eb-93a7-cede254ee152.png)

**Comment by karolis-sh** [comment]
can you provide a working example in `codesandbox`? e.g. https://codesandbox.io/s/tailwind-bootstrap-grid-kxb8h?file=/tailwind.config.js

**Comment by radovanobal** [comment]
I have sent you a share for the codesandbox.io with a working example for the .no-gutter

**Comment by karolis-sh** [comment]
> I have sent you a share for the codesandbox.io with a working example for the .no-gutter

I checked the fork, don't really understand where's the issue

**Comment by radovanobal** [comment]
I have commented out the fix for the issue. 
If you look at the in container no-gutter, it does nothing.

**Comment by karolis-sh** [comment]
Ah I see, the `important: true` breaks the functionality. When you enable it not all of the classes generated by this plugin get the `!important` on each property - this looks like a legit bug.

**Comment by karolis-sh** [comment]
The general root cause (plugin not respecting the `important` config option) is fixed and release.
