### ISSUE TITLE
.row.no-gutters > [class*="md\:col-"] styles are absent after building.

### ISSUE THREAD

**Issue by rromikas** [karolis-sh/tailwind-bootstrap-grid#76]
I noticed that in production environment paddings are not set to 0 in columns that are inside div with class "row no-gutters", while before building these paddings are zeros.

**Comment by ksh-ns** [comment]
https://tailwind-bootstrap-grid.netlify.app/main.css classes seem to be there. My guess would be that you purged too much for a production build.

**Comment by rromikas** [comment]
This is tailwind.config.json file of that app: https://github.com/rromikas/pathways/blob/master/tailwind.config.js
Is it configured to purge too much?

**Comment by karolis-sh** [comment]
Sorry, I do not have time to analyze your project. If the classes are present in development, but not in production after purging, then obviously you're purging too much. It's not only the setup that matters but also app code that you write - https://tailwindcss.com/docs/optimizing-for-production#writing-purgeable-html
