### ISSUE TITLE
Support for responsive variants of containers

### ISSUE THREAD

**Issue by dumptyd** [karolis-sh/tailwind-bootstrap-grid#95]
Great plugin! It would be cool if there was support for responsive variants of containers.

My use case is to be able to do something like this:

```html
<!-- not a container on xs, container-fluid from md onwards, container from lg onwards -->
<div class="md:container-fluid lg:container">...</div>
<!-- or the opposite -->
<div class="md:container lg:container-fluid">...</div>
```

**Comment by karolis-sh** [comment]
Thanks. I'm not certain if this would achieve any real-life use case, as `.container` has left/right paddings which compensate on negative margin on `.row`. What are you trying to achieve, actually? Remove the `max-width` from container?

**Comment by karolis-sh** [comment]
Yeah, that option should cover your needs. In theory, switching between `container` and `container-fluid` might be a use case in the future, but I guess for now I'll be leaving the API as is.
